### ISSUE TITLE
Incorrect Link For Java Library in Readme.md

### ISSUE THREAD

**Issue by flamespinner** [REVrobotics/SPARK-MAX-Examples#13]
The link for the Java API libraries in the Readme.md is outdated and causes issues with the newest Spark Max firmware (1.5.2). Robot Code Crashes when uploaded and ran with the current linked Libraries (1.4.x).

Error is the following: 
SparkMaxDriver could not be loaded from path or an embedded resources

**Comment by willtoth** [comment]
Fixed, thanks
